name: "Setup Nix Flake Environment"
description: "Setup Nix Flake Environment"
inputs:
  system:
    description: "target system"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Nix (with flakes)
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=github:nixos/nixpkgs/nixpkgs-unstable

    - name: Enable flakes support
      shell: bash
      run: |
        mkdir -p ~/.config/nix
        echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

    - name: Build devShell
      shell: bash
      run: |
        nix build .#devShells.${{ inputs.system }}.default
